-- supabase/schema.public.sql
--
-- Derived secondary reference for the current public-schema contracts that matter
-- to this repo. This file is intentionally NOT the canonical migration history.
--
-- Canonical source of truth (SoT):
--   1) supabase/migrations/*.sql
--   2) DB/RPC invariant tests under __tests__/
--
-- Use this file as a quick contract snapshot only.
-- Historical drift (for example the temporary uuid-returning
-- insert_diagnostic_upload(jsonb) variant and legacy repo/branch/mode/platform/
-- report/meta payload mapping) is documented in migrations/tests and is NOT
-- repeated here as if it were still current.

-- =============================================================================
-- CURRENT SNAPSHOT: diagnostics upload contracts
-- =============================================================================

create table if not exists public.diagnostic_uploads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  device_id text not null,
  client_request_id uuid not null default gen_random_uuid(),
  app_version text null,
  project_name text null,
  target text null,
  summary jsonb null,
  snapshots jsonb null,
  notes text null,
  ip inet null
);

create unique index if not exists diagnostic_uploads_device_client_request_uidx
  on public.diagnostic_uploads (device_id, client_request_id);

-- Direct table reads are intentionally not the client contract.
-- Final RLS/grant posture from migrations:
--   - anon/authenticated: no read access to public.diagnostic_uploads
--   - writes happen via SECURITY DEFINER RPC below
--   - service_role retains privileged access via Supabase role behavior

-- Function contract snapshot only (non-executable reference). See:
--   - 20260315000100_finalize_insert_diagnostic_upload_contract.sql
--   - 20260320000000_restore_insert_diagnostic_upload_anon_client_contract.sql
-- Signature:
--   public.insert_diagnostic_upload(payload jsonb) -> bigint
-- Runtime shape:
--   language plpgsql
--   security definer
--   set search_path = public
-- Effective payload keys:
--   device_id, client_request_id, app_version, project_name, target,
--   summary, snapshots, notes
-- Effective write target:
--   public.diagnostic_uploads(device_id, client_request_id, app_version,
--   project_name, target, summary, snapshots, notes, ip)
-- Effective auth/grants:
--   execute for anon, authenticated, service_role
-- This snapshot intentionally omits the executable function body so the
-- canonical implementation stays in migration history.

-- =============================================================================
-- CURRENT SNAPSHOT: diagnostics history table used by tooling
-- =============================================================================

create table if not exists public.diagnostics_reports (
  id bigint generated by default as identity primary key,
  github_repo text not null,
  branch text null,
  status text not null,
  project_id text null,
  workflow_run_id text null,
  commit_sha text null,
  expo_config jsonb null,
  errors jsonb null,
  created_at timestamptz not null default now()
);

-- Final RLS posture from migrations:
--   - anon/authenticated reads are denied by policy
--   - no public diagnostics history RPC is part of the current app contract
--   - privileged/internal tooling must rely on migration-defined access paths
