// Auto-extracted from lib/diagnostics/preflightChecks.ts
import type { ProjectFile } from "../../../shared/types/project";
import type { PreflightCheck } from "../preflightTypes";
import {
  normalizePath, byPath, has, getText, ok, mkFix, mkJsonFix,
  existsAny, ensureEndsWithNewline,
  gitignoreAppendMissing, npmrcLockfileSetting,
} from "../preflightHelpers";
import {
  buildWithoutCredentialsPatch,
  collectForbiddenFileHits,
  collectMissingGitignoreEntries,
  GITIGNORE_TEMPLATE,
  parseAssetCandidates,
  parseEasJson,
  readNativeDirState,
  readWithoutCredentialsEnabled,
} from "./assetsAndFiles.helpers";

export const checkAssetsExist: PreflightCheck = {
  id: "assets-exist",
  title: "Assets referenced existieren",
  severity: "normal",
  run(files) {
    const m = byPath(files);
    const cfgPath = existsAny(m, [
      "app.json",
      "app.config.js",
      "app.config.ts",
      "app.config.json",
    ]);

    if (!cfgPath) {
      return ok({
        id: this.id,
        title: this.title,
        severity: this.severity,
        status: "warn",
        message: "Keine app.json/app.config.* gefunden.",
      });
    }

    const cfgText = getText(m, cfgPath);

    const candidates = parseAssetCandidates(cfgText);

    if (!candidates.length) {
      return ok({
        id: this.id,
        title: this.title,
        severity: this.severity,
        status: "pass",
        message: "Keine Asset-Refs gefunden.",
      });
    }

    const missing = candidates.filter((p) => !has(m, p));
    if (!missing.length)
      return ok({ id: this.id, title: this.title, severity: this.severity });

    return {
      id: this.id,
      title: this.title,
      severity: this.severity,
      status: "warn",
      message: `Asset-Dateien fehlen (${missing.length}).`,
      details: missing.slice(0, 50),
    };
  },
};

// --- Extra quality checks ---


export const checkLockfileConsistency: PreflightCheck = {
  id: "lockfile-consistency",
  title: "Lockfile Konsistenz",
  severity: "normal",
  run(files) {
    const m = byPath(files);
    if (!has(m, "package.json")) {
      return ok({ id: this.id, title: this.title, severity: this.severity });
    }

    const hasNpm = has(m, "package-lock.json");
    const hasYarn = has(m, "yarn.lock");
    const hasPnpm = has(m, "pnpm-lock.yaml");
    const lockCount = [hasNpm, hasYarn, hasPnpm].filter(Boolean).length;

    if (lockCount === 0) {
      const npmrc = has(m, ".npmrc") ? getText(m, ".npmrc") : "";
      const setting = npmrc ? npmrcLockfileSetting(npmrc) : null;

      if (setting === true) {
        return ok({
          id: this.id,
          title: this.title,
          severity: this.severity,
          status: "pass",
          message:
            "Kein Lockfile im Source – wird beim Install generiert (.npmrc: package-lock=true).",
        });
      }

      if (setting === false) {
        return {
          id: this.id,
          title: this.title,
          severity: this.severity,
          status: "warn",
          message:
            "Kein Lockfile im Source und .npmrc deaktiviert package-lock (package-lock=false). Builds können dadurch inkonsistent werden.",
          fix: {
            patch: mkFix(
              [
                {
                  path: ".npmrc",
                  content: ensureEndsWithNewline(
                    (npmrc || "").replace(
                      /(^|\n)\s*package-lock\s*=\s*(false|0)\s*(\n|$)/im,
                      "$1package-lock=true$3",
                    ) ||
                      "# Generated by k1w1 diagnostics\npackage-lock=true\nsave-exact=true\n",
                  ),
                },
              ],
              [],
              ".npmrc korrigieren (package-lock=true)",
            ),
          },
        };
      }

      return {
        id: this.id,
        title: this.title,
        severity: this.severity,
        status: "warn",
        message:
          "Kein Lockfile gefunden (package-lock.json / yarn.lock / pnpm-lock.yaml). Builds können dadurch inkonsistent werden.",
        fix: {
          patch: mkFix(
            [
              {
                path: ".npmrc",
                content: ensureEndsWithNewline(
                  "# Generated by k1w1 diagnostics\npackage-lock=true\nsave-exact=true\n",
                ),
              },
            ],
            [],
            ".npmrc anlegen (Lockfile beim Install erzwingen)",
          ),
        },
      };
    }

    if (lockCount > 1) {
      const details = [
        hasNpm ? "package-lock.json" : null,
        hasYarn ? "yarn.lock" : null,
        hasPnpm ? "pnpm-lock.yaml" : null,
      ].filter(Boolean) as string[];

      // default preference: pnpm > npm > yarn
      const keep = hasPnpm
        ? "pnpm-lock.yaml"
        : hasNpm
          ? "package-lock.json"
          : "yarn.lock";

      const del: string[] = [];
      if (keep !== "package-lock.json" && hasNpm) del.push("package-lock.json");
      if (keep !== "yarn.lock" && hasYarn) del.push("yarn.lock");
      if (keep !== "pnpm-lock.yaml" && hasPnpm) del.push("pnpm-lock.yaml");

      return {
        id: this.id,
        title: this.title,
        severity: this.severity,
        status: "warn",
        message: `Mehrere Lockfiles gefunden (${details.length}). Nutze nur EINEN Package Manager.`,
        details,
        fix: del.length
          ? {
              patch: mkFix(
                [],
                del,
                `Zusätzliche Lockfiles entfernen (behalte: ${keep})`,
              ),
            }
          : undefined,
      };
    }

    return ok({ id: this.id, title: this.title, severity: this.severity });
  },
};


export const checkGitignorePresent: PreflightCheck = {
  id: "gitignore-present",
  title: ".gitignore vorhanden",
  severity: "normal",
  run(files) {
    const m = byPath(files);

    if (has(m, ".gitignore")) {
      const content = getText(m, ".gitignore");

      // keep this list small + relevant for exported projects
      const misses = collectMissingGitignoreEntries(content);

      if (misses.length) {
        const next = gitignoreAppendMissing(content, misses);
        return {
          id: this.id,
          title: this.title,
          severity: this.severity,
          status: "warn",
          message: ".gitignore wirkt unvollständig (häufige Einträge fehlen).",
          details: misses,
          fix:
            next.trim() && next.trim() !== content.trim()
              ? {
                  patch: mkFix(
                    [{ path: ".gitignore", content: next }],
                    [],
                    "Fehlende .gitignore Einträge ergänzen",
                  ),
                }
              : undefined,
        };
      }

      return ok({ id: this.id, title: this.title, severity: this.severity });
    }

    return {
      id: this.id,
      title: this.title,
      severity: this.severity,
      status: "fail",
      message: ".gitignore fehlt im Projekt.",
      fix: {
        patch: mkFix(
          [{ path: ".gitignore", content: GITIGNORE_TEMPLATE }],
          [],
          ".gitignore erzeugen",
        ),
      },
    };
  },
};

export const checkForbiddenFiles: PreflightCheck = {
  id: "security-forbidden-files",
  title: "Security: verbotene/gefährliche Dateien",
  severity: "high",
  run(files) {
    const hits = collectForbiddenFileHits(files);

    if (!hits.length) {
      return ok({ id: this.id, title: this.title, severity: this.severity });
    }

    return {
      id: this.id,
      title: this.title,
      severity: this.severity,
      status: "fail",
      message: "Potentiell gefährliche Dateien/Secrets gefunden.",
      details: hits.slice(0, 50),
    };
  },
};



export const checkNativeDirsManagedGuard: PreflightCheck = {
  id: "native-dirs-managed-guard",
  title: "Native Ordner Konsistenz (Android-only)",
  severity: "normal",
  run(files) {
    const { androidLooksIncomplete, iosLooksIncomplete } = readNativeDirState(files);

    if (androidLooksIncomplete || iosLooksIncomplete) {
      const details: string[] = [];
      if (androidLooksIncomplete) details.push("android/ vorhanden, aber android/app/build.gradle fehlt.");
      if (iosLooksIncomplete) details.push("ios/ vorhanden, aber ios/Podfile fehlt (iOS wird hier nicht genutzt).");

      return {
        id: this.id,
        title: this.title,
        severity: this.severity,
        status: "warn",
        message:
          "Unvollständige native Ordner können den EAS Build brechen. Hinweis: Dieses Projekt ist Android-only – ein halb-existierendes ios/ ist besonders gefährlich.",
        details,
      };
    }

    return ok({ id: this.id, title: this.title, severity: this.severity });
  },
};

export const checkEasWithoutCredentialsForDebug: PreflightCheck = {
  id: "eas-withoutcredentials-debug",
  title: "EAS Debug Builds ohne Keystore",
  severity: "normal",
  run(files) {
    const m = byPath(files);
    if (!has(m, "eas.json")) return ok({ id: this.id, title: this.title, severity: this.severity });

    const eas = parseEasJson(getText(m, "eas.json"));
    if (!eas) {
      return {
        id: this.id,
        title: this.title,
        severity: this.severity,
        status: "warn",
        message: "eas.json konnte nicht geparst werden.",
      };
    }

    const devOk = readWithoutCredentialsEnabled(eas, "development");
    const prevOk = readWithoutCredentialsEnabled(eas, "preview");

    if (!devOk || !prevOk) {
      const missing: string[] = [];
      if (!devOk) missing.push('eas.json: build.development.android.withoutCredentials=true fehlt');
      if (!prevOk) missing.push('eas.json: build.preview.android.withoutCredentials=true fehlt');

      const patchObj = buildWithoutCredentialsPatch({ devOk, previewOk: prevOk });

      return {
        id: this.id,
        title: this.title,
        severity: this.severity,
        status: "warn",
        message:
          "Ohne Keystore kann EAS in CI (--non-interactive) keinen neuen Keystore erzeugen. Für Debug/APK Builds sollte withoutCredentials=true gesetzt sein.",
        details: missing,
        fix: {
          patch: mkJsonFix(
            [
              {
                path: "eas.json",
                patch: { build: patchObj },
                createIfMissing: false,
              },
            ],
            [],
            "withoutCredentials=true für development/preview setzen",
          ),
        },
      };
    }

    return ok({ id: this.id, title: this.title, severity: this.severity });
  },
};
