// Auto-extracted from lib/diagnostics/preflightChecks.ts
import type { ProjectFile } from "../../../shared/types/project";
import type { PreflightCheck } from "../preflightTypes";
import {
  normalizePath, byPath, has, getText, ok, mkFix, mkJsonFix,
  existsAny, parseJson, ensureEndsWithNewline,
  gitignoreAppendMissing, npmrcLockfileSetting,
} from "../preflightHelpers";

type EasWithoutCredentialsPatchProfile = Readonly<{
  android: Readonly<{
    withoutCredentials: true;
  }>;
}>;

type EasProfileConfig = Readonly<{
  android?: Readonly<{
    withoutCredentials?: boolean;
  }>;
}>;

type EasJson = Readonly<{
  build?: Readonly<Record<string, EasProfileConfig | undefined>>;
}>;

export const checkAssetsExist: PreflightCheck = {
  id: "assets-exist",
  title: "Assets referenced existieren",
  severity: "normal",
  run(files) {
    const m = byPath(files);
    const cfgPath = existsAny(m, [
      "app.json",
      "app.config.js",
      "app.config.ts",
      "app.config.json",
    ]);

    if (!cfgPath) {
      return ok({
        id: this.id,
        title: this.title,
        severity: this.severity,
        status: "warn",
        message: "Keine app.json/app.config.* gefunden.",
      });
    }

    const cfgText = getText(m, cfgPath);

    const iconMatches = [...cfgText.matchAll(/"icon"\s*:\s*"([^"]+)"/g)]
      .map((x) => x[1])
      .filter(Boolean);

    const splashMatches = [...cfgText.matchAll(/"image"\s*:\s*"([^"]+)"/g)]
      .map((x) => x[1])
      .filter(Boolean);

    const candidates = [...new Set([...iconMatches, ...splashMatches])]
      .map((p) => normalizePath(p.replace(/^\.\//, "")))
      .filter((p) => p && !p.startsWith("http"));

    if (!candidates.length) {
      return ok({
        id: this.id,
        title: this.title,
        severity: this.severity,
        status: "pass",
        message: "Keine Asset-Refs gefunden.",
      });
    }

    const missing = candidates.filter((p) => !has(m, p));
    if (!missing.length)
      return ok({ id: this.id, title: this.title, severity: this.severity });

    return {
      id: this.id,
      title: this.title,
      severity: this.severity,
      status: "warn",
      message: `Asset-Dateien fehlen (${missing.length}).`,
      details: missing.slice(0, 50),
    };
  },
};

// --- Extra quality checks ---


export const checkLockfileConsistency: PreflightCheck = {
  id: "lockfile-consistency",
  title: "Lockfile Konsistenz",
  severity: "normal",
  run(files) {
    const m = byPath(files);
    if (!has(m, "package.json")) {
      return ok({ id: this.id, title: this.title, severity: this.severity });
    }

    const hasNpm = has(m, "package-lock.json");
    const hasYarn = has(m, "yarn.lock");
    const hasPnpm = has(m, "pnpm-lock.yaml");
    const lockCount = [hasNpm, hasYarn, hasPnpm].filter(Boolean).length;

    if (lockCount === 0) {
      const npmrc = has(m, ".npmrc") ? getText(m, ".npmrc") : "";
      const setting = npmrc ? npmrcLockfileSetting(npmrc) : null;

      if (setting === true) {
        return ok({
          id: this.id,
          title: this.title,
          severity: this.severity,
          status: "pass",
          message:
            "Kein Lockfile im Source – wird beim Install generiert (.npmrc: package-lock=true).",
        });
      }

      if (setting === false) {
        return {
          id: this.id,
          title: this.title,
          severity: this.severity,
          status: "warn",
          message:
            "Kein Lockfile im Source und .npmrc deaktiviert package-lock (package-lock=false). Builds können dadurch inkonsistent werden.",
          fix: {
            patch: mkFix(
              [
                {
                  path: ".npmrc",
                  content: ensureEndsWithNewline(
                    (npmrc || "").replace(
                      /(^|\n)\s*package-lock\s*=\s*(false|0)\s*(\n|$)/im,
                      "$1package-lock=true$3",
                    ) ||
                      "# Generated by k1w1 diagnostics\npackage-lock=true\nsave-exact=true\n",
                  ),
                },
              ],
              [],
              ".npmrc korrigieren (package-lock=true)",
            ),
          },
        };
      }

      return {
        id: this.id,
        title: this.title,
        severity: this.severity,
        status: "warn",
        message:
          "Kein Lockfile gefunden (package-lock.json / yarn.lock / pnpm-lock.yaml). Builds können dadurch inkonsistent werden.",
        fix: {
          patch: mkFix(
            [
              {
                path: ".npmrc",
                content: ensureEndsWithNewline(
                  "# Generated by k1w1 diagnostics\npackage-lock=true\nsave-exact=true\n",
                ),
              },
            ],
            [],
            ".npmrc anlegen (Lockfile beim Install erzwingen)",
          ),
        },
      };
    }

    if (lockCount > 1) {
      const details = [
        hasNpm ? "package-lock.json" : null,
        hasYarn ? "yarn.lock" : null,
        hasPnpm ? "pnpm-lock.yaml" : null,
      ].filter(Boolean) as string[];

      // default preference: pnpm > npm > yarn
      const keep = hasPnpm
        ? "pnpm-lock.yaml"
        : hasNpm
          ? "package-lock.json"
          : "yarn.lock";

      const del: string[] = [];
      if (keep !== "package-lock.json" && hasNpm) del.push("package-lock.json");
      if (keep !== "yarn.lock" && hasYarn) del.push("yarn.lock");
      if (keep !== "pnpm-lock.yaml" && hasPnpm) del.push("pnpm-lock.yaml");

      return {
        id: this.id,
        title: this.title,
        severity: this.severity,
        status: "warn",
        message: `Mehrere Lockfiles gefunden (${details.length}). Nutze nur EINEN Package Manager.`,
        details,
        fix: del.length
          ? {
              patch: mkFix(
                [],
                del,
                `Zusätzliche Lockfiles entfernen (behalte: ${keep})`,
              ),
            }
          : undefined,
      };
    }

    return ok({ id: this.id, title: this.title, severity: this.severity });
  },
};


export const checkGitignorePresent: PreflightCheck = {
  id: "gitignore-present",
  title: ".gitignore vorhanden",
  severity: "normal",
  run(files) {
    const m = byPath(files);

    if (has(m, ".gitignore")) {
      const content = getText(m, ".gitignore");

      // keep this list small + relevant for exported projects
      const misses: string[] = [];
      const mustHave = [
        "node_modules/",
        ".expo/",
        ".expo-shared/",
        ".vscode/",
        ".idea/",
        ".env",
        "dist/",
        "build/",
        "web-build/",
        "*.log",
      ];

      const lowered = content.toLowerCase();
      for (const entry of mustHave) {
        const e = entry.toLowerCase().replace(/\/$/, "");
        // naive but stable: substring check (works for typical ignore lines)
        if (!lowered.includes(e)) misses.push(entry);
      }

      if (misses.length) {
        const next = gitignoreAppendMissing(content, misses);
        return {
          id: this.id,
          title: this.title,
          severity: this.severity,
          status: "warn",
          message: ".gitignore wirkt unvollständig (häufige Einträge fehlen).",
          details: misses,
          fix:
            next.trim() && next.trim() !== content.trim()
              ? {
                  patch: mkFix(
                    [{ path: ".gitignore", content: next }],
                    [],
                    "Fehlende .gitignore Einträge ergänzen",
                  ),
                }
              : undefined,
        };
      }

      return ok({ id: this.id, title: this.title, severity: this.severity });
    }

    const template = `# Dependencies
node_modules/

# Expo
.expo/
.expo-shared/
dist/
web-build/

# Native
android/
ios/
*.jks
*.p8
*.p12
*.key
*.mobileprovision

# IDE
.vscode/
.idea/

# Metro
.metro-health-check*

# Debug
npm-debug.*
yarn-debug.*
yarn-error.*
*.log

# Misc
.DS_Store

# Env
.env
.env*.local
`;

    return {
      id: this.id,
      title: this.title,
      severity: this.severity,
      status: "fail",
      message: ".gitignore fehlt im Projekt.",
      fix: {
        patch: mkFix(
          [{ path: ".gitignore", content: template }],
          [],
          ".gitignore erzeugen",
        ),
      },
    };
  },
};


const FORBIDDEN_PATTERNS: Array<{ label: string; re: RegExp }> = [
  { label: "Private Keys", re: /BEGIN (RSA|EC|OPENSSH|DSA) PRIVATE KEY/ },
  { label: "Android Keystore", re: /\.jks$|\.keystore$/i },
];

export const checkForbiddenFiles: PreflightCheck = {
  id: "security-forbidden-files",
  title: "Security: verbotene/gefährliche Dateien",
  severity: "high",
  run(files) {
    const hitsSet = new Set<string>();

    for (const f of files) {
      const p = normalizePath(f.path);
      const content = f.content ?? "";

      // fast path: forbidden by filename/extension
      let matchedByName = false;
      for (const pat of FORBIDDEN_PATTERNS) {
        if (pat.re.test(p)) {
          hitsSet.add(`${p} (${pat.label})`);
          matchedByName = true;
          break;
        }
      }

      // huge content heuristic BEFORE scanning content (perf)
      if (content.length > 2_000_000) {
        hitsSet.add(
          `${p} (sehr groß: ${Math.round(content.length / 1024 / 1024)}MB in content)`,
        );
        continue;
      }

      // if the filename already flagged it, don't add a duplicate from content scan
      if (matchedByName) continue;

      // now scan content (safe size)
      for (const pat of FORBIDDEN_PATTERNS) {
        if (pat.re.test(content)) {
          hitsSet.add(`${p} (${pat.label})`);
          break;
        }
      }
    }

    const hits = Array.from(hitsSet);

    if (!hits.length) {
      return ok({ id: this.id, title: this.title, severity: this.severity });
    }

    return {
      id: this.id,
      title: this.title,
      severity: this.severity,
      status: "fail",
      message: "Potentiell gefährliche Dateien/Secrets gefunden.",
      details: hits.slice(0, 50),
    };
  },
};



export const checkNativeDirsManagedGuard: PreflightCheck = {
  id: "native-dirs-managed-guard",
  title: "Native Ordner Konsistenz (Android-only)",
  severity: "normal",
  run(files) {
    const m = byPath(files);

    const hasAndroidDir = files.some((f) => f.path === "android" || f.path.startsWith("android/"));
    const hasIosDir = files.some((f) => f.path === "ios" || f.path.startsWith("ios/"));

    const androidLooksIncomplete =
      hasAndroidDir && !(has(m, "android/app/build.gradle") || has(m, "android/app/build.gradle.kts"));

    const iosLooksIncomplete = hasIosDir && !has(m, "ios/Podfile");

    if (androidLooksIncomplete || iosLooksIncomplete) {
      const details: string[] = [];
      if (androidLooksIncomplete) details.push("android/ vorhanden, aber android/app/build.gradle fehlt.");
      if (iosLooksIncomplete) details.push("ios/ vorhanden, aber ios/Podfile fehlt (iOS wird hier nicht genutzt).");

      return {
        id: this.id,
        title: this.title,
        severity: this.severity,
        status: "warn",
        message:
          "Unvollständige native Ordner können den EAS Build brechen. Hinweis: Dieses Projekt ist Android-only – ein halb-existierendes ios/ ist besonders gefährlich.",
        details,
      };
    }

    return ok({ id: this.id, title: this.title, severity: this.severity });
  },
};

export const checkEasWithoutCredentialsForDebug: PreflightCheck = {
  id: "eas-withoutcredentials-debug",
  title: "EAS Debug Builds ohne Keystore",
  severity: "normal",
  run(files) {
    const m = byPath(files);
    if (!has(m, "eas.json")) return ok({ id: this.id, title: this.title, severity: this.severity });

    const eas = parseJson<EasJson>(getText(m, "eas.json"));
    if (!eas) {
      return {
        id: this.id,
        title: this.title,
        severity: this.severity,
        status: "warn",
        message: "eas.json konnte nicht geparst werden.",
      };
    }

    const build = eas.build ?? {};
    const checkProfile = (name: string) => {
      const v = build[name]?.android?.withoutCredentials;
      return v === true;
    };

    const devOk = checkProfile("development");
    const prevOk = checkProfile("preview");

    if (!devOk || !prevOk) {
      const missing: string[] = [];
      if (!devOk) missing.push('eas.json: build.development.android.withoutCredentials=true fehlt');
      if (!prevOk) missing.push('eas.json: build.preview.android.withoutCredentials=true fehlt');

      const patchObj: Partial<
        Record<"development" | "preview", EasWithoutCredentialsPatchProfile>
      > = {};
      if (!devOk) patchObj.development = { android: { withoutCredentials: true } };
      if (!prevOk) patchObj.preview = { android: { withoutCredentials: true } };

      return {
        id: this.id,
        title: this.title,
        severity: this.severity,
        status: "warn",
        message:
          "Ohne Keystore kann EAS in CI (--non-interactive) keinen neuen Keystore erzeugen. Für Debug/APK Builds sollte withoutCredentials=true gesetzt sein.",
        details: missing,
        fix: {
          patch: mkJsonFix(
            [
              {
                path: "eas.json",
                patch: { build: patchObj },
                createIfMissing: false,
              },
            ],
            [],
            "withoutCredentials=true für development/preview setzen",
          ),
        },
      };
    }

    return ok({ id: this.id, title: this.title, severity: this.severity });
  },
};
