// screens/GitHubReposScreen/components/BranchSelector.styles.ts
import { StyleSheet } from "react-native";
import { theme } from "../../../theme";

export const s = StyleSheet.create({
  container: {
    marginBottom: 12,
    borderRadius: 14,
    backgroundColor: theme.palette.card,
    borderWidth: 1,
    borderColor: theme.palette.border,
    overflow: "hidden",
  },
  selector: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 14,
  },
  selectorTextWrap: {
    flex: 1,
    gap: 2,
  },
  selectorLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: theme.palette.text.muted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  selectorValue: {
    fontSize: 14,
    fontWeight: "700",
    color: theme.palette.primary,
  },
  actionIconBtn: {
    width: 32,
    height: 32,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: theme.palette.border,
    backgroundColor: theme.palette.secondary,
  },
  dropdown: {
    maxHeight: 200,
    borderTopWidth: 1,
    borderTopColor: theme.palette.border,
  },
  searchWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.palette.border,
    backgroundColor: theme.palette.card,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: theme.palette.text.primary,
    paddingVertical: 4,
  },
  clearBtn: {
    padding: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.palette.border,
  },
  recentWrap: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 6,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.palette.border,
  },
  recentTitle: {
    fontSize: 10,
    fontWeight: "800",
    color: theme.palette.text.muted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  recentRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  recentPill: {
    maxWidth: "100%",
    borderWidth: 1,
    borderColor: theme.palette.border,
    backgroundColor: theme.palette.background,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
  },
  recentPillText: {
    fontSize: 12,
    color: theme.palette.primary,
    fontWeight: "700",
    maxWidth: 220,
  },
  dropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: theme.palette.border,
  },
  dropdownItemActive: {
    backgroundColor: "rgba(0,255,0,0.06)",
  },
  dropdownText: {
    fontSize: 13,
    color: theme.palette.text.primary,
    fontWeight: "600",
    flex: 1,
  },
  dropdownTextActive: {
    color: theme.palette.primary,
    fontWeight: "800",
  },
  empty: {
    padding: 14,
    fontSize: 12,
    color: theme.palette.text.secondary,
    textAlign: "center",
  },
});
