import { StyleSheet } from "react-native";
import { theme } from "../theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.palette.background,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    position: "relative",
  },
  glowOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: `${theme.palette.error}08`,
  },
  errorCard: {
    backgroundColor: theme.palette.card,
    borderRadius: 20,
    padding: 24,
    borderWidth: 2,
    borderColor: theme.palette.error,
    maxWidth: 400,
    width: "100%",
  },
  iconContainer: {
    alignItems: "center",
    marginBottom: 20,
  },
  iconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: `${theme.palette.error}15`,
    borderWidth: 2,
    borderColor: theme.palette.error,
    alignItems: "center",
    justifyContent: "center",
  },
  errorTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: theme.palette.text.primary,
    marginBottom: 16,
    textAlign: "center",
  },
  errorMessageContainer: {
    backgroundColor: `${theme.palette.error}10`,
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: `${theme.palette.error}30`,
  },
  errorMessage: {
    fontSize: 14,
    color: theme.palette.error,
    lineHeight: 22,
    textAlign: "center",
    fontFamily: "monospace",
  },
  devSection: {
    marginBottom: 16,
  },
  devSectionTitle: {
    fontSize: 12,
    fontWeight: "600",
    color: theme.palette.text.secondary,
    marginBottom: 8,
  },
  stackTrace: {
    backgroundColor: theme.palette.background,
    borderRadius: 8,
    padding: 12,
    maxHeight: 150,
    borderWidth: 1,
    borderColor: theme.palette.border,
  },
  stackTraceText: {
    fontSize: 10,
    fontFamily: "monospace",
    color: theme.palette.text.secondary,
    lineHeight: 16,
  },
  resetButton: {
    backgroundColor: theme.palette.primary,
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginBottom: 12,
  },
  resetButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#000",
  },
  hintText: {
    fontSize: 12,
    color: theme.palette.text.disabled,
    textAlign: "center",
    fontStyle: "italic",
  },
});
