import { StyleSheet } from 'react-native';

import { theme } from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.palette.background,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: theme.palette.card,
    borderBottomWidth: 1,
    borderBottomColor: theme.palette.border,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: theme.palette.text.primary,
  },
  exportButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: theme.palette.primary,
  },
  exportButtonText: {
    color: theme.palette.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  loadingText: {
    marginTop: 12,
    color: theme.palette.text.secondary,
    fontSize: 16,
  },
  errorText: {
    marginTop: 16,
    fontSize: 18,
    fontWeight: '600',
    color: theme.palette.error,
    textAlign: 'center',
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: theme.palette.card,
    borderBottomWidth: 1,
    borderBottomColor: theme.palette.border,
  },
  tab: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    gap: 4,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabActive: {
    borderBottomColor: theme.palette.primary,
  },
  tabText: {
    fontSize: 11,
    color: theme.palette.text.secondary,
    fontWeight: '500',
  },
  tabTextActive: {
    color: theme.palette.primary,
    fontWeight: '600',
  },
  content: {
    flex: 1,
  },
  section: {
    padding: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: theme.palette.text.primary,
    marginBottom: 16,
  },
  card: {
    backgroundColor: theme.palette.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.palette.border,
    padding: 16,
    marginBottom: 16,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.palette.border,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.palette.text.primary,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 16,
  },
  statCard: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: theme.palette.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.palette.border,
    padding: 16,
    alignItems: 'center',
    gap: 8,
  },
  statNumber: {
    fontSize: 24,
    fontWeight: '700',
    color: theme.palette.primary,
  },
  statLabel: {
    fontSize: 12,
    color: theme.palette.text.secondary,
    textAlign: 'center',
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: theme.palette.border + '30',
  },
  infoLabel: {
    fontSize: 14,
    color: theme.palette.text.secondary,
    fontWeight: '500',
  },
  infoValue: {
    fontSize: 14,
    color: theme.palette.text.primary,
    fontWeight: '600',
    maxWidth: '60%',
    textAlign: 'right',
  },
  checklistItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 8,
  },
  checklistText: {
    fontSize: 14,
    color: theme.palette.text.primary,
  },
  infoCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    backgroundColor: theme.palette.card,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.palette.warning + '40',
    padding: 12,
    marginBottom: 16,
  },
  infoCardText: {
    flex: 1,
    fontSize: 13,
    color: theme.palette.text.secondary,
    lineHeight: 18,
  },
  depItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: theme.palette.border + '20',
  },
  depDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: theme.palette.primary,
  },
  depContent: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  depName: {
    fontSize: 13,
    color: theme.palette.text.primary,
    fontWeight: '500',
  },
  depVersion: {
    fontSize: 12,
    color: theme.palette.text.secondary,
    fontFamily: 'monospace',
  },
  fileItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 4,
  },
  fileName: {
    fontSize: 13,
    color: theme.palette.text.secondary,
    fontFamily: 'monospace',
  },
  emptyText: {
    fontSize: 14,
    color: theme.palette.text.secondary,
    textAlign: 'center',
    fontStyle: 'italic',
    paddingVertical: 12,
  },
  validationCard: {
    backgroundColor: theme.palette.card,
    borderRadius: 8,
    borderWidth: 1,
    borderLeftWidth: 4,
    padding: 12,
    marginBottom: 12,
  },
  validationCardError: {
    borderLeftColor: theme.palette.error,
    borderColor: theme.palette.error + '40',
  },
  validationCardWarning: {
    borderLeftColor: theme.palette.warning,
    borderColor: theme.palette.warning + '40',
  },
  validationCardInfo: {
    borderLeftColor: theme.palette.success,
    borderColor: theme.palette.success + '40',
  },
  validationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  validationMessage: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
  },
  validationMessageError: {
    color: theme.palette.error,
  },
  validationMessageWarning: {
    color: theme.palette.warning,
  },
  validationMessageInfo: {
    color: theme.palette.success,
  },
  validationDetails: {
    fontSize: 13,
    color: theme.palette.text.secondary,
    marginTop: 6,
    marginLeft: 32,
    lineHeight: 18,
  },
});
