import { theme } from "../../../theme";

export const keyManagementStyles = {
  providerPickerRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
    marginBottom: 10,
  },
  providerChip: {
    borderWidth: 1,
    borderColor: theme.palette.border,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: theme.palette.background,
  },
  providerChipActive: { borderColor: theme.palette.primary },
  providerChipText: {
    color: theme.palette.text.secondary,
    fontWeight: "900",
    fontSize: 12,
  },
  providerChipTextActive: { color: theme.palette.primary },
  keyRow: { flexDirection: "row", gap: 10, alignItems: "center" },
  keyInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: theme.palette.border,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: theme.palette.text.primary,
    backgroundColor: theme.palette.background,
  },
  keyAddBtn: {
    borderRadius: 16,
    backgroundColor: "transparent",
    borderWidth: 1.5,
    borderColor: theme.palette.primary,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    gap: 6,
    alignItems: "center",
  },
  keyAddBtnText: { fontWeight: "900", color: theme.palette.primary },
  keyList: { marginTop: 12, gap: 10 },
  keyItem: {
    borderWidth: 1,
    borderColor: theme.palette.border,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: theme.palette.background,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  keyText: { flex: 1, color: theme.palette.text.primary, fontSize: 12 },
  keyActions: { flexDirection: "row", gap: 8 },
  keyActionBtn: {
    width: 34,
    height: 34,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: theme.palette.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.palette.card,
  },
  keyActionDanger: { borderColor: theme.palette.error + "55" },
  rotateBtn: {
    marginTop: 12,
    borderRadius: 16,
    backgroundColor: "transparent",
    borderWidth: 1.5,
    borderColor: theme.palette.primary,
    paddingVertical: 12,
    paddingHorizontal: 12,
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  rotateBtnText: { fontWeight: "900", color: theme.palette.primary },
  agentToggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    gap: 12,
  },
  agentToggleLabel: {
    color: theme.palette.text.primary,
    fontWeight: "900",
    fontSize: 13,
  },
  agentTogglePills: { flexDirection: "row", gap: 8 },
  agentTogglePill: {
    borderWidth: 1,
    borderColor: theme.palette.border,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: "transparent",
    minWidth: 64,
    alignItems: "center",
  },
  agentTogglePillActive: {
    borderColor: theme.palette.primary,
    backgroundColor: theme.palette.primary + "22",
  },
  agentTogglePillActiveOff: {
    borderColor: theme.palette.error,
    backgroundColor: theme.palette.error + "18",
  },
  agentTogglePillText: {
    color: theme.palette.text.secondary,
    fontWeight: "900",
  },
  agentTogglePillTextActive: { color: theme.palette.primary },
  agentTogglePillTextActiveOff: { color: theme.palette.error },
  agentToggleHint: {
    color: theme.palette.text.secondary,
    fontSize: 12,
    marginBottom: 6,
  },
  notifyBtn: {
    marginTop: 10,
    borderRadius: 16,
    backgroundColor: "transparent",
    borderWidth: 1.5,
    borderColor: theme.palette.primary,
    paddingVertical: 12,
    paddingHorizontal: 12,
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  notifyBtnText: { fontWeight: "900", color: theme.palette.primary },
  tokenPreview: {
    marginTop: 8,
    color: theme.palette.text.secondary,
    fontSize: 12,
  },
} as const;
