import { theme } from "../../../theme";

export const mainStyles = {
  safe: { flex: 1, backgroundColor: theme.palette.background },
  container: { flex: 1, padding: 16 },
  h1: {
    fontSize: 24,
    fontWeight: "900",
    color: theme.palette.text.primary,
    marginBottom: 12,
  },
  h2: {
    fontSize: 16,
    fontWeight: "900",
    color: theme.palette.text.primary,
    marginBottom: 12,
  },
  h3: {
    fontSize: 13,
    fontWeight: "900",
    color: theme.palette.text.secondary,
    marginTop: 10,
    marginBottom: 8,
  },
  card: {
    backgroundColor: theme.palette.card,
    borderWidth: 1,
    borderColor: theme.palette.border,
    borderRadius: 18,
    padding: 14,
    marginBottom: 14,
  },
  providerTile: {
    borderWidth: 1,
    borderColor: theme.palette.border,
    borderRadius: 16,
    padding: 12,
    marginBottom: 10,
    backgroundColor: theme.palette.background,
  },
  providerTileActive: {
    borderColor: theme.palette.primary,
    shadowColor: theme.palette.primary,
    elevation: 3,
  },
  providerTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 6,
  },
  providerTitle: {
    fontWeight: "900",
    color: theme.palette.text.primary,
    fontSize: 14,
  },
  providerDesc: {
    color: theme.palette.text.secondary,
    fontSize: 12,
    lineHeight: 18,
  },
  providerFoot: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 10,
  },
  providerKeys: { color: theme.palette.text.secondary, fontSize: 12 },
  providerKeysStrong: { color: theme.palette.text.primary, fontWeight: "900" },
  statusLamp: {
    width: 10,
    height: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: theme.palette.border,
  },
  statusLampOk: {
    backgroundColor: theme.palette.primary,
    borderColor: theme.palette.primary,
  },
  statusLampIdle: {
    backgroundColor: theme.palette.border,
    borderColor: theme.palette.border,
  },
  statusLampAlert: {
    backgroundColor: theme.palette.error,
    borderColor: theme.palette.error,
  },
  alertBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: theme.palette.error + "22",
  },
  alertBadgeText: {
    color: theme.palette.error,
    fontWeight: "900",
    fontSize: 11,
  },
  emptyText: { color: theme.palette.text.secondary, fontSize: 12 },
  modeList: { gap: 10 },
  modeTile: {
    borderWidth: 1,
    borderColor: theme.palette.border,
    borderRadius: 16,
    padding: 12,
    backgroundColor: theme.palette.background,
  },
  modeTileActive: { borderColor: theme.palette.primary },
  modeTileHighlight: { borderColor: "#7c4dff" },
  modeHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  modeTitle: {
    fontWeight: "900",
    color: theme.palette.text.primary,
    fontSize: 13,
  },
  modeTitleActive: { color: theme.palette.primary },
  tierToken: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 999 },
  tierTokenText: { fontWeight: "900", fontSize: 11 },
  modeDesc: { color: theme.palette.text.secondary, fontSize: 12, marginTop: 6 },
  modeFoot: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 10,
  },
  personaBadge: {
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    fontWeight: "900",
    fontSize: 11,
  },
  bestFor: { color: theme.palette.text.secondary, fontSize: 12, flex: 1 },
  modeMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  metaPill: {
    borderWidth: 1,
    borderColor: `${theme.palette.primary}33`,
    backgroundColor: `${theme.palette.primary}11`,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  metaPillText: {
    color: theme.palette.text.secondary,
    fontSize: 11,
    fontWeight: "700",
  },
  qualityRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  qualityBtn: {
    borderWidth: 1,
    borderColor: theme.palette.border,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  qualityBtnActive: { borderColor: theme.palette.primary },
  qualityBtnText: { fontWeight: "900", fontSize: 12 },
  qualityBtnTextActive: { color: theme.palette.primary },
  note: {
    marginTop: 10,
    color: theme.palette.text.secondary,
    fontSize: 12,
    lineHeight: 18,
  },
  noteStrong: { color: theme.palette.text.primary, fontWeight: "900" },
  privacyRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  privacyTextCol: { flex: 1, minWidth: 0 },
  privacyLabel: { color: theme.palette.text.primary, fontWeight: "900", fontSize: 13 },
  privacyHint: { color: theme.palette.text.secondary, fontSize: 12, marginTop: 4, lineHeight: 18 },
  retentionEditor: { marginTop: 12 },
  retentionLabel: {
    color: theme.palette.text.secondary,
    fontSize: 12,
    marginBottom: 6,
  },
  retentionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  retentionInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: theme.palette.border,
    borderRadius: 12,
    color: theme.palette.text.primary,
    backgroundColor: theme.palette.background,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontWeight: "700",
  },
  retentionSaveBtn: {
    borderWidth: 1,
    borderColor: theme.palette.primary,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  retentionSaveBtnText: {
    color: theme.palette.primary,
    fontWeight: "900",
    fontSize: 12,
  },
} as const;
