// screens/EnhancedBuildScreen/components/OneClickDeployCard.styles.ts
// Extracted from OneClickDeployCard.tsx
import { StyleSheet } from "react-native";
import { theme } from "../../../theme";

export const s = StyleSheet.create({
  card: {
    marginTop: 14,
    marginHorizontal: 16,
    backgroundColor: theme.palette.card,
    borderWidth: 1,
    borderColor: theme.palette.border,
    borderRadius: 16,
    padding: 16,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
  },
  title: {
    flex: 1,
    color: theme.palette.text.primary,
    fontWeight: "900",
    fontSize: 16,
  },
  doneBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: theme.palette.success,
    backgroundColor: "rgba(0,255,0,0.06)",
  },
  doneBadgeText: {
    color: theme.palette.success,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1,
  },
  timeline: { gap: 4 },
  stepRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "transparent",
    position: "relative",
  },
  stepRowOk: {
    borderColor: "rgba(0,255,0,0.1)",
    backgroundColor: "rgba(0,255,0,0.02)",
  },
  stepRowFail: {
    borderColor: "rgba(255,68,68,0.15)",
    backgroundColor: "rgba(255,68,68,0.03)",
  },
  stepRowRunning: {
    borderColor: "rgba(0,255,0,0.15)",
    backgroundColor: "rgba(0,255,0,0.03)",
  },
  stepTextWrap: { flex: 1 },
  stepLabel: {
    color: theme.palette.text.secondary,
    fontSize: 14,
    fontWeight: "700",
  },
  stepLabelOk: { color: theme.palette.text.primary },
  stepLabelFail: { color: theme.palette.error },
  stepDetail: {
    color: theme.palette.text.muted,
    fontSize: 11,
    marginTop: 2,
  },
  connectorWrap: {
    position: "absolute",
    left: 21,
    bottom: -6,
    height: 8,
    width: 2,
    zIndex: -1,
  },
  connector: {
    flex: 1,
    width: 2,
    backgroundColor: theme.palette.border,
  },
  connectorOk: {
    backgroundColor: theme.palette.success,
  },
  optionRow: {
    marginTop: 16,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: theme.palette.border,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  optionTextWrap: {
    flex: 1,
  },
  optionLabel: {
    color: theme.palette.text.primary,
    fontSize: 13,
    fontWeight: "800",
  },
  optionHint: {
    marginTop: 2,
    color: theme.palette.text.muted,
    fontSize: 11,
  },
  optionLamp: {
    minWidth: 44,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: "center",
  },
  optionLampOn: {
    borderColor: theme.palette.success,
    backgroundColor: "rgba(0,255,0,0.08)",
  },
  optionLampOff: {
    borderColor: theme.palette.text.disabled,
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  optionLampText: {
    color: theme.palette.text.secondary,
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  actions: {
    marginTop: 16,
  },
  deployBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: theme.palette.primary,
    backgroundColor: "transparent",
  },
  deployBtnText: {
    color: theme.palette.primary,
    fontSize: 15,
    fontWeight: "900",
  },
  abortBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.palette.error,
    backgroundColor: "transparent",
  },
  abortBtnText: {
    color: theme.palette.error,
    fontSize: 14,
    fontWeight: "800",
  },
  retryBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.palette.warning,
    backgroundColor: "transparent",
  },
  retryBtnText: {
    color: theme.palette.warning,
    fontSize: 14,
    fontWeight: "800",
  },
  resetBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.palette.border,
    backgroundColor: "transparent",
  },
  resetBtnText: {
    color: theme.palette.text.secondary,
    fontSize: 14,
    fontWeight: "700",
  },
  disabledBtn: { opacity: 0.4 },
  disabledReason: {
    marginTop: 10,
    color: theme.palette.text.muted,
    fontSize: 12,
    lineHeight: 16,
  },
});
