// screens/EnhancedBuildScreen/components/WorkflowRunDetailModal.styles.ts
// Extracted from WorkflowRunDetailModal.tsx
import { StyleSheet } from "react-native";
import { theme } from "../../../theme";

export const s = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.55)",
    justifyContent: "flex-end",
  },
  sheet: {
    maxHeight: "92%",
    backgroundColor: theme.palette.background,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderWidth: 1,
    borderColor: theme.palette.border,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: theme.palette.border,
    backgroundColor: theme.palette.card,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
  },
  headerTitle: {
    flex: 1,
    fontSize: 14,
    fontWeight: "900",
    color: theme.palette.text.primary,
    paddingRight: 12,
  },
  closeBtn: {
    padding: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.palette.border,
    backgroundColor: theme.palette.background,
  },
  content: {
    padding: 16,
    paddingBottom: 26,
  },
  card: {
    marginTop: 14,
    borderWidth: 1,
    borderColor: theme.palette.border,
    borderRadius: 14,
    padding: 14,
    backgroundColor: theme.palette.card,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: "900",
    color: theme.palette.text.primary,
    marginBottom: 10,
  },
  rowBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  badge: {
    fontSize: 11,
    fontWeight: "900",
    color: theme.palette.primary,
    borderWidth: 1,
    borderColor: theme.palette.border,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: theme.palette.background,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 14,
    marginBottom: 8,
  },
  infoLabel: {
    width: 90,
    fontSize: 11,
    fontWeight: "800",
    color: theme.palette.text.muted,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  infoValue: {
    flex: 1,
    fontSize: 12,
    fontWeight: "600",
    color: theme.palette.text.secondary,
    textAlign: "right",
  },
  mono: {
    fontFamily: "monospace",
  },
  jobCard: {
    borderWidth: 1,
    borderColor: theme.palette.border,
    borderRadius: 12,
    padding: 12,
    backgroundColor: theme.palette.background,
  },
  jobTitle: {
    flex: 1,
    fontSize: 13,
    fontWeight: "800",
    color: theme.palette.text.primary,
    paddingRight: 10,
  },
  jobId: {
    fontSize: 11,
    fontWeight: "900",
    color: theme.palette.text.muted,
  },
  jobMeta: {
    fontSize: 12,
    color: theme.palette.text.secondary,
    marginTop: 6,
  },
  jobActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
  },
  smallBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.palette.border,
    backgroundColor: theme.palette.card,
    marginLeft: 10,
  },
  smallBtnText: {
    fontSize: 12,
    color: theme.palette.primary,
    fontWeight: "800",
  },
  jobBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.palette.border,
    backgroundColor: theme.palette.card,
  },
  jobBtnText: {
    fontSize: 12,
    color: theme.palette.primary,
    fontWeight: "800",
  },
  stepLine: {
    fontSize: 11,
    color: theme.palette.text.secondary,
  },
  muted: {
    fontSize: 12,
    color: theme.palette.text.secondary,
  },

});

