
-- supabase/migrations/20260105000100_build_jobs.sql
-- Adds the missing build_jobs table used by:
-- - supabase/functions/trigger-eas-build
-- - supabase/functions/check-eas-build

create table if not exists public.build_jobs (
  id bigint generated by default as identity primary key,
  github_repo text not null,
  build_profile text not null default 'preview',
  status text not null default 'queued',

  github_run_id text,
  eas_build_id text,
  build_url text,
  error_message text,

  started_at timestamptz,
  completed_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Ensure columns exist (idempotent)
alter table if exists public.build_jobs add column if not exists github_repo text;
alter table if exists public.build_jobs add column if not exists build_profile text;
alter table if exists public.build_jobs add column if not exists status text;

alter table if exists public.build_jobs add column if not exists github_run_id text;
alter table if exists public.build_jobs add column if not exists eas_build_id text;
alter table if exists public.build_jobs add column if not exists build_url text;
alter table if exists public.build_jobs add column if not exists error_message text;

alter table if exists public.build_jobs add column if not exists started_at timestamptz;
alter table if exists public.build_jobs add column if not exists completed_at timestamptz;

alter table if exists public.build_jobs add column if not exists created_at timestamptz;
alter table if exists public.build_jobs add column if not exists updated_at timestamptz;

-- Set defaults only if they are currently NULL
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'build_jobs'
      and column_name = 'build_profile'
      and column_default is null
  ) then
    alter table public.build_jobs alter column build_profile set default 'preview';
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'build_jobs'
      and column_name = 'status'
      and column_default is null
  ) then
    alter table public.build_jobs alter column status set default 'queued';
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'build_jobs'
      and column_name = 'created_at'
      and column_default is null
  ) then
    alter table public.build_jobs alter column created_at set default now();
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'build_jobs'
      and column_name = 'updated_at'
      and column_default is null
  ) then
    alter table public.build_jobs alter column updated_at set default now();
  end if;
end $$;

-- Constraints
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'build_jobs_build_profile_chk'
  ) then
    alter table public.build_jobs
      add constraint build_jobs_build_profile_chk
      check (build_profile in ('development','preview','production'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'build_jobs_status_chk'
  ) then
    alter table public.build_jobs
      add constraint build_jobs_status_chk
      check (status in ('queued','building','completed','success','failed','error','waiting','unknown'));
  end if;
end $$;

-- updated_at trigger
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $fn$
begin
  new.updated_at = now();
  return new;
end;
$fn$;

drop trigger if exists set_build_jobs_updated_at on public.build_jobs;
create trigger set_build_jobs_updated_at
before update on public.build_jobs
for each row execute function public.set_updated_at();

-- RLS
alter table public.build_jobs enable row level security;

drop policy if exists "Service role full access" on public.build_jobs;
create policy "Service role full access"
on public.build_jobs
for all
to service_role
using (true)
with check (true);

drop policy if exists "Public read build_jobs" on public.build_jobs;
create policy "Public read build_jobs"
on public.build_jobs
for select
to anon
using (true);

grant select on table public.build_jobs to anon, authenticated;
grant all on table public.build_jobs to service_role;

create index if not exists build_jobs_created_at_idx on public.build_jobs (created_at desc);
create index if not exists build_jobs_status_idx on public.build_jobs (status);
