-- supabase/migrations/20260110000100_diagnostics_reports.sql
-- Diagnostics reports from GitHub Actions (k1w1-diagnostics workflow)

create table if not exists public.diagnostics_reports (
  id bigint generated by default as identity primary key,
  github_repo text not null,
  branch text,
  status text not null, -- 'pass' | 'fail'
  project_id text,
  workflow_run_id text,
  commit_sha text,
  expo_config jsonb,
  errors jsonb,
  created_at timestamptz not null default now()
);

alter table public.diagnostics_reports enable row level security;

drop policy if exists "Public read diagnostics_reports" on public.diagnostics_reports;
create policy "Public read diagnostics_reports"
on public.diagnostics_reports
for select
to anon
using (true);

grant select on table public.diagnostics_reports to anon, authenticated;
grant all on table public.diagnostics_reports to service_role;

create index if not exists diagnostics_reports_created_at_idx
  on public.diagnostics_reports (created_at desc);

create index if not exists diagnostics_reports_repo_branch_idx
  on public.diagnostics_reports (github_repo, branch, created_at desc);
