-- Patch 561: durable edge rate-limit events for high-risk routes.
-- Honest contract: this is a lightweight durable counter table (not a perfect global lock).

create table if not exists public.edge_rate_limit_events (
  id bigint generated by default as identity primary key,
  scope text not null,
  subject text not null,
  created_at timestamptz not null default now()
);

create index if not exists edge_rate_limit_events_scope_subject_created_idx
  on public.edge_rate_limit_events (scope, subject, created_at desc);

alter table public.edge_rate_limit_events enable row level security;

-- Explicit deny policy for non-service callers.
drop policy if exists "Deny read edge_rate_limit_events" on public.edge_rate_limit_events;
create policy "Deny read edge_rate_limit_events"
  on public.edge_rate_limit_events
  for select
  to authenticated, anon
  using (false);

drop policy if exists "Deny write edge_rate_limit_events" on public.edge_rate_limit_events;
create policy "Deny write edge_rate_limit_events"
  on public.edge_rate_limit_events
  for all
  to authenticated, anon
  using (false)
  with check (false);

revoke all on table public.edge_rate_limit_events from anon;
revoke all on table public.edge_rate_limit_events from authenticated;
grant all on table public.edge_rate_limit_events to service_role;

-- Retention note (operator-managed):
-- This table is append-only by design for a short-window counter.
-- Recommended housekeeping (e.g. scheduled SQL job) is to delete old rows:
--   delete from public.edge_rate_limit_events where created_at < now() - interval '7 days';
