-- supabase/migrations/20260105000100_build_jobs.sql
-- Build job tracking table used by trigger-eas-build / check-eas-build

create table if not exists public.build_jobs (
  id bigint generated by default as identity primary key,
  github_repo text not null,
  build_profile text not null default 'preview',
  branch text,
  status text not null default 'queued',
  github_run_id text,
  eas_build_id text,
  build_url text,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.build_jobs
  add column if not exists branch text;

-- RLS
alter table public.build_jobs enable row level security;

drop policy if exists "Public read build_jobs" on public.build_jobs;
create policy "Public read build_jobs"
on public.build_jobs
for select
to anon
using (true);

grant select on table public.build_jobs to anon, authenticated;
grant all on table public.build_jobs to service_role;

create index if not exists build_jobs_created_at_idx on public.build_jobs (created_at desc);
create index if not exists build_jobs_status_idx on public.build_jobs (status);
