-- supabase/migrations/20260112000100_diagnostic_uploads.sql

-- Anonymous uploads are allowed by design for this app.
-- Security is handled by strict row-size limits + per-device rate limiting in a trigger.

create table if not exists public.diagnostic_uploads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  device_id text not null,
  app_version text null,
  project_name text null,
  target text null,
  summary jsonb null,
  snapshots jsonb null,
  notes text null,
  ip inet null
);

alter table public.diagnostic_uploads enable row level security;

-- Hard row size guardrails (in addition to app-side truncation)
create or replace function public._diagnostic_upload_guard()
returns trigger
language plpgsql
security definer
as $$
declare
  per_hour integer;
  per_day integer;
  max_hour integer := 10;
  max_day integer := 50;
  max_notes integer := 2000;
  max_snapshots_bytes integer := 150000;
  snap_text text;
begin
  if new.device_id is null or length(new.device_id) < 8 then
    raise exception 'device_id missing/invalid';
  end if;

  if new.notes is not null and length(new.notes) > max_notes then
    new.notes := left(new.notes, max_notes) || '…';
  end if;

  -- store IP if available
  begin
    new.ip := inet_client_addr();
  exception when others then
    -- ignore
  end;

  -- Rate limits (per device)
  select count(*) into per_hour
  from public.diagnostic_uploads
  where device_id = new.device_id
    and created_at > now() - interval '1 hour';

  if per_hour >= max_hour then
    raise exception 'rate limit exceeded (per hour)';
  end if;

  select count(*) into per_day
  from public.diagnostic_uploads
  where device_id = new.device_id
    and created_at > now() - interval '24 hours';

  if per_day >= max_day then
    raise exception 'rate limit exceeded (per day)';
  end if;

  -- Payload size guard (snapshots can be large)
  snap_text := coalesce(new.snapshots::text, '');
  if octet_length(snap_text) > max_snapshots_bytes then
    raise exception 'payload too large';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_diagnostic_upload_guard on public.diagnostic_uploads;
create trigger trg_diagnostic_upload_guard
before insert on public.diagnostic_uploads
for each row execute function public._diagnostic_upload_guard();

-- Allow anonymous insert only (no select/update/delete by anon)
drop policy if exists diagnostic_uploads_insert_anon on public.diagnostic_uploads;
create policy diagnostic_uploads_insert_anon
  on public.diagnostic_uploads
  for insert
  to anon
  with check (true);

-- Optional: allow authenticated users to read their own (not used yet)
drop policy if exists diagnostic_uploads_select_authenticated on public.diagnostic_uploads;
create policy diagnostic_uploads_select_authenticated
  on public.diagnostic_uploads
  for select
  to authenticated
  using (true);
