// screens/PreviewScreen/PreviewScreen.styles.ts
import { StyleSheet } from "react-native";
import { theme } from "../../theme";

export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: theme.palette.background },
  screenContent: { flex: 1, minHeight: 0 },
  screenScrollContent: { flexGrow: 1 },
  screenScrollContentShort: { paddingBottom: 0 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24, gap: 12 },
  loadingText: { color: theme.palette.text.secondary, fontWeight: '700', fontSize: 14 },
  emptyTitle: { color: theme.palette.text.primary, fontSize: 18, fontWeight: '900' },
  emptyText: { color: theme.palette.text.secondary, fontSize: 14, textAlign: 'center' },
  toolbar: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    flexWrap: 'wrap',
    paddingHorizontal: 14, paddingVertical: 10,
    borderBottomWidth: 1, borderBottomColor: theme.palette.border,
    backgroundColor: theme.palette.card,
    gap: 10,
  },
  toolbarCompact: { alignItems: 'flex-start' },
  toolbarLeft: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1, minWidth: 0 },
  toolbarLeftCompact: { width: '100%', flexBasis: '100%' },
  toolbarTitle: { flex: 1, minWidth: 0 },
  title: { color: theme.palette.text.primary, fontSize: 18, fontWeight: '900' },
  subtitle: { color: theme.palette.text.secondary, fontSize: 12 },
  toolbarActions: {
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexShrink: 1,
    flexWrap: 'wrap',
  },
  toolbarActionsCompact: { width: '100%', justifyContent: 'flex-start' },
  toolbarRuntimeHint: {
    width: '100%',
    color: theme.palette.text.muted,
    fontSize: 10,
    fontWeight: '700',
  },
  toolBtn: {
    width: 36, height: 36, borderRadius: 10, borderWidth: 1,
    borderColor: theme.palette.border, backgroundColor: theme.palette.background,
    alignItems: 'center', justifyContent: 'center',
  },
  hotReloadBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 5,
    paddingHorizontal: 10, paddingVertical: 7,
    borderRadius: 10, borderWidth: 1,
    borderColor: theme.palette.border, backgroundColor: theme.palette.background,
  },
  hotReloadBtnOn: { borderColor: theme.palette.primary, backgroundColor: 'rgba(0,255,0,0.06)' },
  hotDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: theme.palette.text.disabled },
  hotDotOn: {
    backgroundColor: theme.palette.primary,
    shadowColor: theme.palette.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8, shadowRadius: 4,
  },
  hotReloadLabel: { fontSize: 11, fontWeight: '900', color: theme.palette.text.muted, letterSpacing: 0.3 },
  hotReloadLabelOn: { color: theme.palette.primary },
  statusBarWrap: {
    borderBottomWidth: 1, borderBottomColor: theme.palette.border,
    backgroundColor: theme.palette.backgroundDark,
  },
  statusBar: {
    flexDirection: 'row', alignItems: 'center', gap: 8,
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    paddingHorizontal: 14, paddingVertical: 8,
  },
  statusBarCompact: { alignItems: 'flex-start' },
  statusHeadline: { flexDirection: 'row', alignItems: 'center', gap: 8, flex: 1, minWidth: 180 },
  statusMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap', justifyContent: 'flex-end' },
  statusMetaRowCompact: { width: '100%', justifyContent: 'flex-start' },
  statusDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: theme.palette.text.disabled },
  statusDotNeutral: { backgroundColor: theme.palette.text.disabled },
  statusDotOk: {
    backgroundColor: theme.palette.success,
    shadowColor: theme.palette.success,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6, shadowRadius: 4,
  },
  statusDotError: { backgroundColor: theme.palette.error },
  statusDotWarning: { backgroundColor: theme.palette.warning },
  statusDotLoading: { backgroundColor: theme.palette.warning },
  statusText: { flex: 1, color: theme.palette.text.secondary, fontSize: 12, fontWeight: '700' },
  previewStatsText: { color: theme.palette.text.muted, fontSize: 11, fontWeight: '700' },
  statusBadge: {
    paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999, borderWidth: 1,
  },
  statusBadgeOk: {
    borderColor: 'rgba(0,255,0,0.2)', backgroundColor: 'rgba(0,255,0,0.06)',
  },
  statusBadgeWarning: {
    borderColor: 'rgba(255,170,0,0.25)', backgroundColor: 'rgba(255,170,0,0.08)',
  },
  statusBadgeError: {
    borderColor: 'rgba(255,68,68,0.25)', backgroundColor: 'rgba(255,68,68,0.08)',
  },
  statusBadgeNeutral: {
    borderColor: theme.palette.border, backgroundColor: 'rgba(255,255,255,0.03)',
  },
  statusBadgeText: { color: theme.palette.text.primary, fontSize: 10, fontWeight: '800' },
  hotBadge: {
    paddingHorizontal: 8, paddingVertical: 3, borderRadius: 999, borderWidth: 1,
    borderColor: 'rgba(0,255,0,0.2)', backgroundColor: 'rgba(0,255,0,0.06)',
  },
  hotBadgeText: { color: theme.palette.primary, fontSize: 10, fontWeight: '800' },
  previewInfoBar: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    flexWrap: 'wrap',
    paddingHorizontal: 14, paddingBottom: 8,
  },
  previewInfoBarCompact: { alignItems: 'flex-start' },
  previewInfoBullet: { color: theme.palette.text.muted, fontSize: 11, fontWeight: '700' },
  previewInfoText: { color: theme.palette.text.muted, fontSize: 11, fontWeight: '700' },
  previewNoticeBar: {
    paddingHorizontal: 14,
    paddingBottom: 10,
  },
  previewNoticeText: {
    color: theme.palette.warning,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 16,
    flexShrink: 1,
  },
  previewRuntimeBar: {
    paddingHorizontal: 14,
    paddingBottom: 10,
  },
  previewRuntimeText: {
    color: theme.palette.text.disabled,
    fontSize: 10,
    fontWeight: '700',
  },
  previewBody: {
    flex: 1,
    minHeight: 0,
    backgroundColor: theme.palette.backgroundDark,
  },
  previewBodyShort: {
    flexGrow: 1,
  },
  previewArea: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    justifyContent: 'flex-start',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    backgroundColor: theme.palette.backgroundDark,
  },
  deviceFrame: {
    flex: 1,
    minHeight: 280,
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    backgroundColor: '#111', borderRadius: 24, borderWidth: 2,
    borderColor: theme.palette.border, overflow: 'hidden',
    shadowColor: '#000', shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3, shadowRadius: 12, elevation: 8,
  },
  deviceNotch: {
    height: 6, backgroundColor: '#0a0a0a',
    borderBottomLeftRadius: 8, borderBottomRightRadius: 8,
    marginHorizontal: '30%', marginBottom: 2,
  },
  deviceBottom: {
    height: 4, backgroundColor: '#0a0a0a',
    borderTopLeftRadius: 8, borderTopRightRadius: 8,
    marginHorizontal: '40%', marginTop: 2,
  },
  webViewWrap: { flex: 1, minHeight: 0, backgroundColor: '#fff' },
  webView: { flex: 1, backgroundColor: '#fff' },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(5,8,12,0.28)',
    alignItems: 'center', justifyContent: 'center', padding: 20,
  },
  loadingOverlayCard: {
    minWidth: 220,
    maxWidth: '100%',
    gap: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(0,255,0,0.2)',
    backgroundColor: 'rgba(6,10,16,0.88)',
  },
  loadingOverlayText: { color: '#fff', fontSize: 13, fontWeight: '700', textAlign: 'center' },
  emptyPreview: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 16, padding: 24, backgroundColor: '#0d1117' },
  emptyPreviewTitle: { color: theme.palette.text.primary, fontSize: 18, fontWeight: '800', textAlign: 'center' },
  emptyPreviewText: { color: theme.palette.text.muted, fontSize: 14, fontWeight: '700', textAlign: 'center', lineHeight: 20 },
  createBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    paddingHorizontal: 20, paddingVertical: 12,
    borderRadius: 12, borderWidth: 1.5, borderColor: theme.palette.primary,
  },
  createBtnText: { color: theme.palette.primary, fontSize: 14, fontWeight: '800' },
  previewMetaStack: {
    paddingHorizontal: 14,
    paddingBottom: 10,
    gap: 10,
    backgroundColor: theme.palette.backgroundDark,
  },
  diagnosticCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,170,0,0.35)',
    backgroundColor: 'rgba(255,170,0,0.08)',
    padding: 10,
    gap: 8,
  },
  diagnosticText: {
    color: theme.palette.warning,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
  },
  urlCard: {
    borderRadius: 12, borderWidth: 1, borderColor: theme.palette.border,
    backgroundColor: theme.palette.card, padding: 10, gap: 8,
  },
  urlCardHeader: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  urlCardTitle: { color: theme.palette.text.primary, fontSize: 12, fontWeight: '800' },
  urlText: { color: theme.palette.text.secondary, fontSize: 12, fontWeight: '600' },
  urlActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  urlBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    borderWidth: 1, borderColor: theme.palette.border, borderRadius: 999,
    paddingHorizontal: 10, paddingVertical: 6,
  },
  urlBtnText: { color: theme.palette.text.secondary, fontSize: 11, fontWeight: '700' },
  urlBtnTextPrimary: { color: theme.palette.primary },
  errorBar: {
    flexDirection: 'row', alignItems: 'center', gap: 8,
    paddingHorizontal: 14, paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    backgroundColor: 'rgba(255,68,68,0.08)',
    borderColor: theme.palette.error,
  },
  errorText: { flex: 1, color: theme.palette.error, fontSize: 12, fontWeight: '600' },
  errorRetryBtn: {
    paddingHorizontal: 12, paddingVertical: 6,
    borderRadius: 8, borderWidth: 1, borderColor: theme.palette.error,
  },
  errorRetryText: { color: theme.palette.error, fontSize: 12, fontWeight: '800' },
  bottomBar: {
    flexDirection: 'row', gap: 10, paddingHorizontal: 14, paddingVertical: 10,
    borderTopWidth: 1, borderTopColor: theme.palette.border,
    backgroundColor: theme.palette.card,
  },
  bottomBtn: {
    flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: 6, paddingVertical: 12, borderRadius: 12, borderWidth: 1,
    borderColor: theme.palette.border, backgroundColor: 'transparent',
  },
  bottomBtnText: { color: theme.palette.primary, fontSize: 13, fontWeight: '800' },
  disabled: { opacity: 0.5 },
});
