import fs from "node:fs";
import path from "node:path";

const migrationsDir = path.join(process.cwd(), "supabase/migrations");

function readMigration(fileName: string): string {
  return fs.readFileSync(path.join(migrationsDir, fileName), "utf8");
}

describe("patch439 insert_diagnostic_upload history hygiene", () => {
  it("keeps diagnostic_uploads table canonical and free of drift columns", () => {
    const tableSql = readMigration("20260112000100_diagnostic_uploads.sql");

    expect(tableSql).toContain("create table if not exists public.diagnostic_uploads");
    expect(tableSql).toContain("id bigint generated by default as identity primary key");
    expect(tableSql).toContain("summary jsonb null");
    expect(tableSql).toContain("snapshots jsonb null");

    for (const legacyColumn of ["repo", "branch", "mode", "platform", "report", "meta"]) {
      expect(tableSql).not.toMatch(new RegExp(`\\b${legacyColumn}\\b`));
    }
  });

  it("documents uuid drift only in the known historical migrations", () => {
    const expectedUuidDriftFiles = new Set([
      "20260203000000_harden_diagnostics_reports_and_rpc.sql",
      "20260203000002_fix_insert_diagnostic_upload_return_type.sql",
    ]);

    const migrationFiles = fs.readdirSync(migrationsDir).filter((fileName) => fileName.endsWith(".sql"));

    const uuidContractFiles = migrationFiles.filter((fileName) => {
      const sql = readMigration(fileName).toLowerCase();
      return (
        sql.includes("insert_diagnostic_upload(payload jsonb)")
        && sql.includes("returns uuid")
      );
    });

    expect(new Set(uuidContractFiles)).toEqual(expectedUuidDriftFiles);
  });

  it("keeps final rpc contract bigint-backed and mapped to canonical columns", () => {
    const finalizeSql = readMigration("20260315000100_finalize_insert_diagnostic_upload_contract.sql");
    const functionBody = finalizeSql.split("as $$")[1] ?? "";

    expect(finalizeSql).toContain("create or replace function public.insert_diagnostic_upload(payload jsonb)");
    expect(finalizeSql).toContain("returns bigint");
    expect(finalizeSql).toContain("on conflict (device_id, client_request_id)");

    for (const driftColumn of ["repo", "branch", "mode", "platform", "report", "meta"]) {
      expect(functionBody).not.toMatch(new RegExp(`\\b${driftColumn}\\b`));
    }
  });
});
