name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch/Tag/SHA to validate"
        required: true

concurrency:
  group: ci-${{ github.event_name == 'workflow_dispatch' && inputs.ref || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci-core.yml
    secrets:
      EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }}
    with:
      ref: ${{ github.event_name == 'workflow_dispatch' && inputs.ref || github.ref }}
